version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: todo-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Backend API
  backend:
    build: .
    container_name: todo-backend
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/todo-app?authSource=admin
      - JWT_SECRET=fdlkjdfakljdfsljkhfdaslkjhfdsljkhfadsljkhfadsjlkhfjklfdaahjjkhdsfhjkldfj
      - EMAIL_USER=your-email@gmail.com
      - EMAIL_PASS=your-app-password
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  # Frontend (Development)
  frontend:
    build: .
    container_name: todo-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:3000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run dev -- --host

volumes:
  mongodb_data: 